adminUser:
  password: vault:raccoonshimmer/adminUser:password
  username: admin
dashboardAuthID: vault:raccoonshimmer:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:raccoonshimmer:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
parentDNSZone: play-jxaas-live-parent
parentDomain: play-jxaas.live
parentProject: dev-arcalos-domain-name
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:raccoonshimmer/pipelineUser:token
  username: arcalos-bot
prow:
  hmacToken: vault:raccoonshimmer/prow:hmacToken
tenantServiceDBInstance: dev-tenant-service-db:us-east1:dev-jx-tenant-db=tcp:5432
